[package]
name = "resource-detection"
description = "The resource detection can be used to detect resource information from the host"
version = "0.0.1"
edition = "2021"
authors = ["The New Relic Core Agent & Open Standards (CAOS) Team"]
publish = false

[dependencies]
mockall = { workspace = true }
nix = { workspace = true, features = ["hostname"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }
serde_json = { workspace = true }
http = { workspace = true }
bytes = "1.5.0"
ureq = {version = "2.9.1", features = ["http-interop"]}
fs = {path = "../fs/"}

[dev-dependencies]
fs = { path = "../fs", features = ["mocks"] }
