[package]
name = "resource-detection"
description = "The resource detection can be used to detect resource information from the host"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license-file.workspace = true

[dependencies]
nix = { workspace = true, features = ["hostname"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
http = { workspace = true }
fs = { path = "../fs" }
konst = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-link = "0.2.1"
winreg = "0.55"

[dev-dependencies]
assert_matches = { workspace = true }
fs = { path = "../fs", features = ["mocks"] }
mockall = { workspace = true }
