[package]
name = "resource-detection"
description = "The resource detection can be used to detect resource information from the host"
version = "0.0.1"
edition = "2021"
authors = ["The New Relic Core Agent & Open Standards (CAOS) Team"]
publish = false

[dependencies]
mockall = "0.12.0"
nix = { version = "0.27.1", features = ["hostname"] }
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.51"
tracing = "0.1.40"
ulid = "1.1.0"
serde_json = "1.0.108"
http = "0.2"
bytes = "1.5.0"
ureq = {version = "2.9.1", features = ["http-interop"]}
fs = {path = "../fs/"}
