# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  # Hold ourselves to a high bar
  range: 80..100
  round: down
  precision: 1
  status:
    # ref: https://docs.codecov.com/docs/commit-status
    project:
      default:
        # Avoid false negatives
        threshold: 1%
        target: 80%

# Test files aren't important for coverage
ignore:
  - "tests"
  - "examples"

comment:
  layout: "reach, diff, flags, files"
  require_changes: false
