name: Set up OCI registry
description: Sets up an OCI registry using zot on port 5000
inputs:
  os:
    description: 'Operating system to run the job on'
    required: true
    type: choice
    options:
      - linux
      - windows
outputs:
  log-file:
    description: 'Path to the zot logs file'
    value: ${{ steps.create-zot-config.outputs.log-file }}
runs:
  using: composite
  steps:
    - name: Download zot
      shell: bash
      run: |
        EXTENSION=${{ inputs.os == 'windows' && '.exe' || '' }}
        echo zot-${{ inputs.os }}-amd64${EXTENSION}
        curl -L https://github.com/project-zot/zot/releases/download/v2.1.11/zot-${{ inputs.os }}-amd64${EXTENSION} --output zot
        chmod +x zot

    - name: Create zot config
      shell: bash
      id: create-zot-config
      run: |
        LOGFILE="zot.log"
        cat << EOF > config.json 
        {
            "distSpecVersion": "1.0.1",
            "storage": {
              "rootDirectory": "/tmp/zot"
            },
            "http": {
              "port": "5000"
            },
            "log": {
              "level": "debug",
              "output": "zot.log"
            }
        }
        EOF
        echo "log-file=$(echo ${LOGFILE})" >> $GITHUB_OUTPUT
    
    - name: Start zot registry
      shell: bash
      run: ./zot serve config.json &
