project_name: newrelic-supervisor
builds:
  -
    main: ./build/dummy.go
    goarch:
      - arm64
    goos:
      - linux
    binary: newrelic-supervisor
    hooks:
      post:
        - sh ./build/build_rust_package.sh
archives:
  - format: gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  # replacements:
  #   darwin: Darwin
  #   linux: Linux
  #   windows: Windows
  #   386: i386
  #   amd64: x86_64
# checksum:
#   name_template: 'checksums.txt'
# release:
#   disable: true