[workspace]
resolver = "3"

members = [
  "agent-control",
  "test/crates/fake-opamp-server",
  "resource-detection",
  "fs",
  "wrapper_with_default",
  "self-replacer",
  "test/e2e-runner",
  "test/crates/oci-test-utils",
]

[workspace.package]
authors = ["The New Relic Agent Control Team"]
edition = "2024"
publish = false
rust-version = "1.97.1"
license-file = "./LICENSE.md"
repository = "https://github.com/newrelic/newrelic-agent-control"

[workspace.dependencies]
serde_json = "1.0.151"
serde = "1.0.229"
tempfile = "3.27.0"
thiserror = "2.0.19"
tracing = "0.1.44"
regex = "1.13.1"
mockall = "0.15.0"
clap = "4.6.6"
flate2 = "1.1.9"
tar = "0.4.46"
nix = "0.31.3"
tracing-subscriber = { version = "0.3.23", features = ["json"] }
tracing-test = "0.2.6"
assert_cmd = "2.2.2"
assert_matches = "1.5.0"
tower-test = "0.4.0"
serde-saphyr = "1.0.1"
schemars = "1.2.2"
http = "1.5.0"
predicates = "3.1.4"
semver = "1.0.28"
chrono = "0.4.45"
jsonwebtoken = { version = "11.0.0", features = ["aws_lc_rs"] }
reqwest = { version = "0.13.4", features = ["blocking", "socks"] }
rstest = "0.26.1"
serial_test = "4.0.1"
windows = "0.62.2"
windows-sys = "0.61.2"
aws-lc-rs = "1.18.0"
opamp-client = { git = "https://github.com/newrelic/newrelic-opamp-rs.git", tag = "0.0.41" }
oci-client = { version = "0.17.0", default-features = false }
tokio = "1.53.1"
base64 = "0.23.1"
actix-web = "4.14.0"
strum = { version = "0.28.0", features = ["derive"] }

[profile.release-debug]
inherits = "release"
debug = 1
