#REGION is where to send the e2e data. Possible values: "US", "EU", "Staging", "Local". See action.yaml for more info.
REGION := "US"
NEWRELIC_E2E := "go run github.com/newrelic/newrelic-integration-e2e-action@latest"

# Default recipe
default:
  just local-e2e-test

# Spin an Ubuntu VM to run the tests
# ubuntu-vm:
#   limactl start --name=ac-onhost-e2e --cpus=1 --memory=1 --network=lima:user-v2 template://ubuntu

# Run the onhost e2e tests
local-e2e-test:
	{{ NEWRELIC_E2E }} \
		--commit_sha=local \
		--retry_attempts=5 \
		--account_id=${ACCOUNT_ID} \
		--api_key=${API_REST_KEY} \
		--license_key=${LICENSE_KEY} \
		--region={{ REGION }} \
		--spec_path=${SPEC_PATH} \
		--verbose_mode=true \
		--agent_enabled="false"
