# -*- mode: Python -*-
# This Tiltfile is used by the integration tests to setup the environment.

update_settings ( k8s_upsert_timeout_secs = 150)

#### Install Flux needed for some integration tests
load('ext://helm_resource', 'helm_repo','helm_resource')

helm_repo(
  'newrelic',
  'https://helm-charts.newrelic.com',
  resource_name='newrelic-helm-repo',
  )

helm_resource(
  'flux',
  'newrelic/agent-control',
  namespace='default',
  release_name='flux',
  update_dependencies=False,
  flags=[
    '--create-namespace',
    '--version=>=0.0.0-beta',
    # Each integration test runs on a different ephimeral namespace.
    '--set=flux2.watchAllNamespaces=true',
    '--set=agent-control-deployment.enabled=false',
    ],
  resource_deps=['newrelic-helm-repo']
)
