
# -*- mode: Python -*-

# This Tiltfile is used by the integration tests to setup the environment.
# Running `tilt ci` in this path will install all resources and waits for Pods to be Ready 
# Currently:
#  - Installs latest Flux version in our super-agent chart.

load('ext://helm_resource', 'helm_repo','helm_resource')
helm_repo(
  'newrelic',
  'https://helm-charts.newrelic.com',
  resource_name='newrelic-helm-repo',
)
  
helm_resource(
  'flux',
  'newrelic/super-agent',
  namespace='default',
  release_name='flux',
  flags=[
    '--create-namespace',
    '--version=>=0.0.0-beta',
    
    '--set=helm.create=false',
    ],
  resource_deps=['newrelic-helm-repo']
)
