ec2_prefix = "onhost-canary-staging"
inventory_output = "environments/staging/inventory.staging"
repository_endpoint = "http://nr-downloads-ohai-testing.s3-website-us-east-1.amazonaws.com/preview"
nr_region = "Staging"
otlp_endpoint = "https://staging-otlp.nr-data.net:4318"
