namespace: newrelic
name: com.newrelic.prometheus
version: 0.1.0
variables:
  k8s:
    chart_values:
      description: "Newrelic prometheus-agent chart values"
      type: yaml
      required: false
      default: {}
    chart_version:
      description: "prometheus-agent chart version"
      type: string
      required: true
deployment:
  k8s:
    health:
      interval: 30s
    objects:
      repository:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        metadata:
          name: ${nr-sub:agent_id}
        spec:
          # Increasing the interval to 30 minutes because the HelmRepository is not as prone to frequent changes
          # as HelmRelease objects might be. Given repositories typically have fewer updates than the resources
          # they trigger, a longer interval helps in reducing unnecessary load on the cluster without significantly
          # delaying the application of important updates.
          interval: 30m
          provider: generic
          url: https://newrelic.github.io/newrelic-prometheus-configurator
      default-values:
        apiVersion: v1
        kind: Secret
        metadata:
          name: default-values-${nr-sub:agent_id}
        stringData:
          values.yaml: |
            licenseKey: ${nr-env:NR_LICENSE_KEY}
            cluster: ${nr-env:NR_CLUSTER_NAME}
      release:
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: ${nr-sub:agent_id}
        spec:
          interval: 3m
          chart:
            spec:
              chart: newrelic-prometheus-agent
              version: ${nr-var:chart_version}
              reconcileStrategy: ChartVersion
              sourceRef:
                kind: HelmRepository
                name: ${nr-sub:agent_id}
              interval: 3m
          install:
            # Wait are disabled to avoid blocking the modifications/deletions of this CR while in reconciling state.
            disableWait: true
            disableWaitForJobs: true
            remediation:
              retries: 3
            replace: true
          upgrade:
            disableWait: true
            disableWaitForJobs: true
            cleanupOnFail: true
            force: true
            remediation:
              retries: 3
              strategy: rollback
          rollback:
            disableWait: true
            disableWaitForJobs: true
          valuesFrom:
          - kind: Secret
            name: default-values-${nr-sub:agent_id}
            valuesKey: values.yaml
          values:
            ${nr-var:chart_values}
