# Docker file used for the installation of the the Agent Control on k8s.

FROM debian:trixie-slim

ARG TARGETARCH
# Automatically bumpled by a Renovate regex rule.
ARG HELM_VERSION=v3.19.0

COPY --chmod=755 bin/newrelic-agent-control-k8s-cli-${TARGETARCH} /bin/newrelic-agent-control-cli

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ca-certificates curl && \
    apt-get clean

# Install latest stable kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/$TARGETARCH/kubectl"&& \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/kubectl

# Install Helm
RUN curl -LO "https://get.helm.sh/helm-$HELM_VERSION-linux-$TARGETARCH.tar.gz" && \
    tar -xzf "helm-$HELM_VERSION-linux-$TARGETARCH.tar.gz" && \
    chmod +x "linux-$TARGETARCH/helm" && \
    mv "linux-$TARGETARCH/helm" /usr/local/bin/helm && \
    rm -rf "helm-$HELM_VERSION-linux-$TARGETARCH.tar.gz" linux-$TARGETARCH

# Create a home directory for nobody user and set ownership
# This is so Helm can actually run as it tries to write to the home directory
RUN mkdir -p /home/nobody && \
    chown nobody:nogroup /home/nobody

USER nobody
ENV HOME=/home/nobody

ENTRYPOINT ["/bin/newrelic-agent-control-cli"]
