# This image is leveraged in the Helm chart in order to create via script the L1 and the secret containing it.
ARG base_image=alpine:3.22

FROM $base_image

RUN apk update
RUN apk add --no-cache kubectl curl jq openssl
