# Docker file use for the released version of the Agent Control.

# Using debian image until the agent control is statically compiled, and move to Alpine.
FROM debian:trixie-slim

ARG TARGETARCH

COPY --chmod=755 bin/newrelic-agent-control-${TARGETARCH} /bin/newrelic-agent-control

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    apt-get upgrade -y && \
    apt-get clean

USER nobody

ENTRYPOINT ["/bin/newrelic-agent-control"]
