[package]
name = "newrelic_super_agent"
description = "New Relic Super Agent Limited Preview"
version = "0.6.2"
edition = "2021"
authors = ["The New Relic Core Agent & Open Standards (CAOS) Team"]
publish = false
default-run = "newrelic-super-agent"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
nix = { workspace = true, features = ["signal", "user", "hostname"] }
log = { workspace = true, features = ["kv_unstable"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing = { workspace = true }
ctrlc = { version = "3.4.0", features = ["termination"] }
serde_yaml = { workspace = true }
regex = { workspace = true }
opamp-client = { git = "ssh://git@github.com/newrelic/opamp-rs.git", tag = "0.0.7" }
futures = "0.3.28"
async-trait = "0.1.71"
tokio = "1.32.0"
ulid = { workspace = true, features = ["serde"] }
openssl = { version = "0.10.57", features = ["vendored"] }
aquamarine = "0.3.2"
duration-str = "0.7.0"
fs = {path = "../fs"}

# OnHost subagent dependencies
# IMPORTANT: All onhost only deps needs to be `optional = true` so they won't be compiled by default
resource-detection = {path = "../resource-detection"}

# K8S subagent dependencies
# IMPORTANT: All k8s only deps needs to be `optional = true` so they won't be compiled by default
kube = { version = "0.87.2", default-features = false, features = [
  "client",
  "openssl-tls",
  "runtime",
  "derive",
], optional = true }
k8s-openapi = { version = "0.20.0", features = ["latest"], optional = true }
either = { version = "1.9.0", optional = true }
crossbeam = { version = "0.8.3", features = ["crossbeam-channel"] }

[dev-dependencies]
assert_cmd = { workspace = true }
assert_fs = { workspace = true }
bollard = { workspace = true }
predicates = { workspace = true }
tower-test = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
tempfile = { workspace = true }
mockall = { workspace = true }
schemars = { workspace = true }
serde_json = { workspace = true }
assert_matches = { workspace = true }
mockall_double = { workspace = true }
tracing-test = { workspace = true }
fs = {path = "../fs", features = ["mocks"]}


[[test]]
name = "k8s"
path = "test/k8s/mod.rs"
required-features = ["k8s"]


[[test]]
name = "on_host"
path = "test/on_host/mod.rs"
required-features = ["onhost"]


[[bin]]
name = "newrelic-super-agent"
path = "src/bin/main.rs"

[features]
onhost = []
k8s = ["dep:kube", "dep:k8s-openapi", "dep:either"]
custom-local-path = []
# feature ci allows calling --all-features (needed on the test pipelines) and not failing to compile
ci = []
