[package]
name = "oci-test-utils"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
aws-lc-rs = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true, features = ["derive"] }
flate2 = { workspace = true }
http = { workspace = true }
oci-client = { workspace = true, features = ["rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde-saphyr = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "rt-multi-thread"] }
actix-web = { workspace = true }
