name: 'Install Rust Toolchain'
description: 'Installs the Rust toolchain version specified in Cargo.toml'
inputs:
  targets:
    description: 'Comma-separated list of additional targets to install'
    required: false
  components:
    description: 'Comma-separated list of additional components to install'
    required: false
runs:
  using: "composite"
  steps:
    - name: Obtain Rust version from project
      shell: bash
      run: |
        RUST_VERSION=$(grep "rust-version" Cargo.toml | cut -d "=" -f2 | tr -d "[:space:]")
        echo "RUST_VERSION=${RUST_VERSION}" >> $GITHUB_ENV

    - name: Install Rust ${{ env.RUST_VERSION }}
      uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
      with:
        toolchain: ${{ env.RUST_VERSION }}
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}
