ec2_prefix = "onhost-canary-production"
inventory_output = "environments/production/inventory.production"
repository_endpoint = "http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/preview"
nr_region = "US"
otlp_endpoint = "https://otlp.nr-data.net:4318"
