permissions:
  contents: read
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: checks
jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Codespell test
        uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461
  fmt:
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CAOS_RUST_CRATES }}
      - name: Install stable
        uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: rustfmt
      - name: Check code formatting
        run: cargo fmt --check

  clippy_packages:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / ${{ matrix.package }} / clippy
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ stable, beta ]
        package: [ config-migrate, fs, license, nr-auth, resource-detection ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CAOS_RUST_CRATES }}

      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@1.78.0
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - name: cargo clippy ${{ matrix.package }}
        run: cargo clippy --package ${{ matrix.package }} --message-format=json --tests -- -D clippy::all

  clippy_super_agent:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / ${{ matrix.feature }} / clippy
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ stable, beta ]
        feature: [ onhost, k8s ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CAOS_RUST_CRATES }}

      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@1.78.0
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - name: cargo clippy super agent (${{ matrix.feature }})
        run: cargo clippy --package newrelic_super_agent --features=${{ matrix.feature }} --message-format=json --tests -- -D clippy::all

  doc:
    runs-on: ubuntu-latest
    name: stable / doc
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CAOS_RUST_CRATES }}
      - name: Install nightly
        uses: dtolnay/rust-toolchain@1.78.0
      - name: Create on-host documentation
        run: cargo doc --no-deps --features=onhost --package newrelic_super_agent
        env:
          RUSTDOCFLAGS: --cfg docsrs
      - name: Create K8s documentation
        run: cargo doc --no-deps --features=k8s --package newrelic_super_agent
        env:
          RUSTDOCFLAGS: --cfg docsrs

  # msrv = Minimum Supported Rust Version
  msrv_super_agent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        msrv: [ 1.78.0 ]
        feature: [ onhost, k8s ]
    name: ubuntu / ${{ matrix.msrv }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CAOS_RUST_CRATES }}

      - name: Install ${{ matrix.msrv }}
        uses: dtolnay/rust-toolchain@1.78.0
        with:
          toolchain: ${{ matrix.msrv }}

      - name: cargo +${{ matrix.msrv }} check ${{ matrix.feature }}
        run: cargo check --package newrelic_super_agent --features=${{ matrix.feature }}

  # msrv = Minimum Supported Rust Version
  msrv_packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        msrv: [ 1.78.0 ]
        package: [ config-migrate, fs, license, nr-auth, resource-detection ]

    name: ubuntu / ${{ matrix.msrv }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CAOS_RUST_CRATES }}

      - name: Install ${{ matrix.msrv }}
        uses: dtolnay/rust-toolchain@1.78.0
        with:
          toolchain: ${{ matrix.msrv }}

      - name: cargo +${{ matrix.msrv }} check ${{ matrix.package }}
        run: cargo check --package ${{ matrix.package }}

  licenses:
    name: Validate third party libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CAOS_RUST_CRATES }}
      - name: Install Rust 1.78.0
        uses: dtolnay/rust-toolchain@1.78.0
      - name: Check security and licensing
        run: cargo install --locked cargo-deny && cargo deny check
      - name: Ensure that third party notices is up to date
        run: make -C license third-party-notices-check
