name: 📞 OnHost E2E tests

on:
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_VPC_SUBNET:
        required: true

    inputs:
      UNIQUE_NAME:
        required: true
        type: string
      PACKAGE_VERSION:
        required: false
        type: string
        default: ""
      REPOSITORY_ENDPOINT:
        required: false
        type: string
        description: 'Repository endpoint to fetch packages from'
        default: "http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/preview"

env:
  UNIQUE_NAME: ${{ inputs.UNIQUE_NAME }}

permissions:
  id-token: write
  contents: read

jobs:
  infra:
    name: Provision infra and run OnHost E2E tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set branch name
        run: |
          make test/e2e \
            ENVIRONMENT=production \
            REPOSITORY_ENDPOINT=${{ inputs.REPOSITORY_ENDPOINT }} \
            PACKAGE_VERSION=${{ inputs.PACKAGE_VERSION }}
