name: 📞 Security image scan
on:
  workflow_call:
    inputs:
      image-tag:
        description: 'Image tag'
        type: string
        required: true

env:
  DOCKER_IMAGE: newrelic/newrelic-agent-control
  SEVERITY: 'CRITICAL,HIGH'

jobs:
  scan:
    name: Scan image
    # Runs only when the trigger is different than a scheduled one, like pull request or push.
    if: ${{ ! github.event.schedule }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy in table mode
        # Table output is only useful when running on a pull request or push.
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}:${{ inputs.image-tag }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: ${{ env.SEVERITY }}
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db

  scan-scheduled:
    name: Scan image
    if: ${{ github.event.schedule }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy in report mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}:${{ inputs.image-tag }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          ignore-unfixed: false  # Get full report when running nightly.
          severity: ${{ env.SEVERITY }}
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db

      # TODO Upload Trivy scan results to GitHub Security tab when the repo gets public state.
      # more info about current limitation https://docs.github.com/en/code-security/code-scanning/troubleshooting-code-scanning/advanced-security-must-be-enabled
