name: 📞 k8s canaries helm update

on:
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_VPC_SUBNET:
        required: true

    inputs:
      image-tag:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      canary_dir:
        description: "Name of the tf directory to run the canary in. Valid values are `production` and `staging`."
        required: true
        type: string

permissions:
  contents: read

env:
  # AC Staging Account `k8s-canaries-staging-1` fleet
  FLEET_ID_STAGING: "MTIyMTMwNjh8TkdFUHxGTEVFVHwwMTk1ZDE1NC1iNTI0LTdhMTYtYWExYS0wYzQ2Y2VhOGFiMzg"
  # AC US Production Account `k8s-canaries-production` fleet
  FLEET_ID_PRODUCTION: "NjQyNTg2NXxOR0VQfEZMRUVUfDAxOTVlYzZhLTYwNjItNzZiZS1iOWE0LTA4MzZlZmE2MGY4YQ"

jobs:
  helm_upgrade:
    name: Helm upgrade canary
    runs-on: ubuntu-latest
    permissions:
      # required to oidc AWS
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Set branch name
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          # Is the ref a tag? If so, remove refs/tags/ prefix
          GIT_BRANCH=${GIT_BRANCH#refs/tags/}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Resolve fleet ID for canary_dir
        run: |
          if [ "${{ inputs.canary_dir }}" = "production" ]; then
            echo "FLEET_ID=${{ env.FLEET_ID_PRODUCTION }}" >> "$GITHUB_ENV"
          else
            echo "FLEET_ID=${{ env.FLEET_ID_STAGING }}" >> "$GITHUB_ENV"
          fi

      - name: Upgrade helm release
        uses: newrelic/fargate-runner-action@121b96de1a4d7135204fd8a510927b0463df1b6b # main
        with:
          aws_region: us-east-2
          container_make_target: "FLEET_ID=${{ env.FLEET_ID }} IMAGE_TAG=${{ inputs.image-tag }} CLUSTER_NAME=${{ inputs.cluster_name }} CANARY_DIR=${{ inputs.canary_dir }} test/k8s-canaries/helm-upgrade"
          ecs_cluster_name: agent_control
          task_definition_name: agent_control
          cloud_watch_logs_group_name: /ecs/test-prerelease-agent_control
          cloud_watch_logs_stream_name: ecs/test-agent_control
          aws_vpc_subnet: ${{ secrets.AWS_VPC_SUBNET }}
          repo_name: ${{ github.repository }}
          git_clone_url: "ssh://git@github.com/${{ github.repository }}.git"
          ref: "${{ env.GIT_BRANCH }}"
