name: Lint PR title

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24.16.0

      - name: Install commitlint with default config
        run: |
          npm i @commitlint/cli
          npm i @commitlint/config-conventional

      - name: Validate PR title
        run: echo '${{ github.event.pull_request.title }}' | npx commitlint --extends @commitlint/config-conventional
