name: 🚀 🧬 Test staging package with molecule action
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version of the agent to test installation'
        required: true

jobs:
  molecule-packaging-tests:
    uses: ./.github/workflows/component_molecule_packaging.yml
    with:
      TAG: ${{ inputs.tag }}
      PACKAGE_NAME: "newrelic-super-agent"
      REPO_ENDPOINT: 'http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/preview'
