name: 🚀 🧬 Test specific version installation
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version of the agent to test installation'
        required: true
      staging:
        description: 'Should run tests using staging bucket?'
        type: boolean
        default: true
        required: false

jobs:
  molecule-packaging-tests:
    uses: ./.github/workflows/component_molecule_packaging.yml
    with:
      TAG: ${{ github.event.inputs.tag }}
      PACKAGE_NAME: "nr-super-agent"
      REPO_ENDPOINT: 'http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/limited_preview'
