name: Nightly release

# Pushes `nightly` image tag as scheduled.

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build-push:
    name: Build and Push nightly image
    uses: ./.github/workflows/component_image.yml
    with:
      image-tag: nightly
      push: true
    secrets: inherit
  
  security-scan:
    name: Security scan
    needs: [build-push]
    uses: ./.github/workflows/component_image_security.yml
    with:
      image-tag: nightly
    secrets: inherit
