name: Nightly release

# Pushes `nightly` image tag as scheduled.

on:
  workflow_dispatch:
  schedule:
    # Scheduled to run at 4 a.m on every day-of-week from Monday through Friday.
    - cron: "0 4 * * 1-5"

jobs:
  build-push:
    name: Build and Push nightly image
    uses: ./.github/workflows/component_image.yml
    with:
      image-tag: nightly
      push: true
    secrets: inherit

  security-scan:
    name: Security scan
    needs: [build-push]
    uses: ./.github/workflows/component_image_security.yml
    with:
      image-tag: nightly
    secrets: inherit

  onhost-e2e:
    uses: ./.github/workflows/component_onhost_e2e.yaml
    with:
      TAG: "0.7.1"
      UNIQUE_NAME: "nightly:e2e"
      EC2_FILTERS: '[\"ubuntu\"]'
      FORCE_CLEANUP: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.TMP_AWS_ROLE_ARN }}
      AWS_VPC_SUBNET: ${{ secrets.TMP_AWS_VPC_SUBNET }}
