name: ⏯️🚀 Build dhat-heap AC image to ghcr.io

# This workflow builds Agent Control container images with the dhat-heap feature enabled
# and pushes them to the GitHub Container Registry.
#
# The resulting images can be used to replace the standard Agent Control image in a
# Kubernetes installation for heap profiling purposes.

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image tag (will be appended to "dhat-heap-")'
        type: string
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Build/Push dhat-heap images
    env:
      DOCKER_PLATFORMS: "linux/amd64,linux/arm64"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/install-rust-toolchain
        with:
          targets: >-
            aarch64-unknown-linux-musl,
            x86_64-unknown-linux-musl

      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile

      - uses: ./.github/actions/rust-cache
        with:
          identifier: 'release'
          restore-strategy: 'nearest'
          save-cache: false

      - name: Install Zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2
        with:
          version: 0.15.2

      - uses: taiki-e/install-action@67729d5c413db75907f0ad1e39bb04b9c868ff60 # v2.85.7
        with:
          tool: cargo-zigbuild@0.20.1

      - name: Build Agent Control for K8s with dhat-heap
        env:
          AGENT_CONTROL_VERSION: dhat-dev-build
          BUILD_MODE: release-debug
          CARGO_FEATURES: dhat-heap
        run: |
          make build-agent-control-k8s ARCH=arm64 PKG=newrelic_agent_control
          make build-agent-control-k8s ARCH=amd64 PKG=newrelic_agent_control

      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4
        with:
          version: v0.36.0

      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dhat-heap images
        run: |
          make image/agent-control \
            DOCKER_PLATFORMS=$DOCKER_PLATFORMS \
            IMAGE_TAG=dhat-heap-${{ inputs.image-tag }} \
            PUSH=true \
            ATTEST=true \
            DOCKER_IMAGE_NAME_AGENT_CONTROL=ghcr.io/${{ github.repository_owner }}/newrelic-agent-control-dev
