name: ⏯️🐤 On-Demand onhost canaries

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (staging/production)"
        required: true
        type: choice
        options:
          - staging
          - production
      package_version:
        description: "Package version (optional, leave empty for latest)"
        required: false
        type: string

permissions:
  contents: read

concurrency:
  group: "on-demand-onhost-canaries-${{ inputs.environment }}"
  cancel-in-progress: false

jobs:
  onhost_canaries_infra:
    name: Canaries infrastructure apply
    uses: ./.github/workflows/component_onhost_canaries_infra.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ inputs.environment }}
      operation: apply
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_VPC_SUBNET: ${{ secrets.AWS_VPC_SUBNET }}
      AC_CANARY_WINDOWS_PASSWORD: ${{ secrets.AC_CANARY_WINDOWS_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.AC_FLEET_COMMON_SLACK_WEBHOOK }}

  onhost_canaries:
    name: Install/Upgrade Agent Control
    uses: ./.github/workflows/component_onhost_canaries.yml
    needs: [ onhost_canaries_infra ]
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ inputs.environment }}
      package_version: ${{ inputs.package_version }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_VPC_SUBNET: ${{ secrets.AWS_VPC_SUBNET }}
