
on:
  pull_request:
    paths:
      - '.github/**'
      - 'build/**'
      - '.goreleaser.yml'

# See https://docs.github.com/en/actions/using-jobs/using-concurrency
name: build-packages
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and upload / ${{ matrix.arch }}
    strategy:
      matrix:
        arch: [arm64, amd64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CAOS_RUST_CRATES }}

      - uses: actions/setup-go@v3
        with:
          go-version: '~1.20'
          check-latest: true

      - name: Build binaries with GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: build --snapshot --clean --debug --timeout 2h --single-target
        env:
          ARCH: "${{ matrix.arch }}"
          GOARCH: "${{ matrix.arch }}"
          GOOS: linux
