name: . 🚀 🐧 🧾 Validate Prerelease Linux On Demand

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and upload / ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CAOS_RUST_CRATES }}

      - name: Tag current codebase
        run: git tag 0.100.0

      - uses: actions/setup-go@v5
        with:
          go-version: '~1.20'
          check-latest: true

      - name: Release packages with GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean --debug --timeout 2h
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
          GPG_MAIL: 'infrastructure-eng@newrelic.com'
          NR_RELEASE_TAG: ${{ github.event.release.tag_name }}

      - name: Upload assets to pipeline
        uses: actions/upload-artifact@v4
        with:
          name: built-binaries
          path: |
            ./bin/*
            ./dist/*
