name: 🐤 Plan onhost canaries infrastructure changes

on:
  push:
    paths:
      - test/onhost-canaries/terraform/infra/**
      - test/onhost-canaries/terraform/alerts/**
      - .github/workflows/component_onhost_canaries_infra.yml
      - .github/workflows/push_pr_onhost_canaries_plan.yml

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: false

jobs:
  infra_plan:
    name: infra plan ${{ matrix.environment }}
    uses: ./.github/workflows/component_onhost_canaries_infra.yml
    strategy:
      fail-fast: false
      matrix:
        environment: [ staging, production ]
    permissions:
      # required to oidc AWS
      id-token: write
      contents: read
    with:
      environment: ${{ matrix.environment }}
      operation: infra-only-plan
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_VPC_SUBNET: ${{ secrets.AWS_VPC_SUBNET }}
      AC_CANARY_WINDOWS_PASSWORD: ${{ secrets.AC_CANARY_WINDOWS_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.AC_SLACK_WEBHOOK }}

  alerts_plan:
    name: alerts plan ${{ matrix.environment }}
    needs: [ infra_plan ]
    uses: ./.github/workflows/component_onhost_canaries_infra.yml
    strategy:
      fail-fast: false
      matrix:
        environment: [ staging, production ]
    permissions:
      # required to oidc AWS
      id-token: write
      contents: read
    with:
      environment: ${{ matrix.environment }}
      operation: alerts-plan
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_VPC_SUBNET: ${{ secrets.AWS_VPC_SUBNET }}
      AC_CANARY_WINDOWS_PASSWORD: ${{ secrets.AC_CANARY_WINDOWS_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.AC_SLACK_WEBHOOK }}
