name: 📞 Build and Push System Identity Registration image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'latest'
  push:
    branches:
      - main
    paths:
      - 'system_identity_registration/**'

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Build and Push System Identity Registration image
    env:
      DOCKER_IMAGE_NAME: newrelic/agent-control-system-identity-registration
      DOCKER_PLATFORMS: "linux/amd64,linux/arm64"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.OHAI_DOCKER_HUB_ID }}
          password: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}

      - name: Build and push image
        run: |
          docker buildx build \
            --push \
            --platform=${DOCKER_PLATFORMS} \
            -t ${DOCKER_IMAGE_NAME}:${{ inputs.tag }} \
            .
