permissions:
  contents: read
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  # Allows to fetch multiple private repo crates with different deploy keys.
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  RUST_VERSION: 1.82.0
name: checks
jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Codespell test
        uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461
  fmt:
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.CAOS_OAUTH_DEPLOY_KEY }}
            ${{ secrets.CAOS_OPAMP_DEPLOY_KEY }}
      - name: Install Rust ${{ env.RUST_VERSION }}
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: ${{ env.RUST_VERSION }}
      - name: Check code formatting
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / ${{ matrix.flag }} / clippy
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ stable, beta ]
        # newrelic_super_agent needs either onhost or k8s feature, the rest of packages can be checked also without features
        flag: [ "--features=onhost", "--features=k8s", "--exclude='newrelic_super_agent'" ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.CAOS_OAUTH_DEPLOY_KEY }}
            ${{ secrets.CAOS_OPAMP_DEPLOY_KEY }}

      - name: Install Rust ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - name: cargo clippy (${{ matrix.flag }})
        run: cargo clippy --workspace ${{ matrix.flag }} --tests -- -D clippy::all

  doc:
    runs-on: ubuntu-latest
    name: stable / doc
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.CAOS_OAUTH_DEPLOY_KEY }}
            ${{ secrets.CAOS_OPAMP_DEPLOY_KEY }}
      - name: Install Rust ${{ env.RUST_VERSION }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Create on-host documentation
        run: cargo doc --no-deps --features=onhost --package newrelic_super_agent
        env:
          RUSTDOCFLAGS: --cfg docsrs
      - name: Create K8s documentation
        run: cargo doc --no-deps --features=k8s --package newrelic_super_agent
        env:
          RUSTDOCFLAGS: --cfg docsrs

  # msrv = Minimum Supported Rust Version
  msrv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        msrv: [ 1.82.0 ]
        # newrelic_super_agent needs either onhost or k8s feature, the rest of packages can be checked also without features
        flag: [ "--features=onhost", "--features=k8s", "--exclude='newrelic_super_agent'" ]
    name: ${{ matrix.msrv }} / ${{ matrix.flag }} / cargo check
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.CAOS_OAUTH_DEPLOY_KEY }}
            ${{ secrets.CAOS_OPAMP_DEPLOY_KEY }}

      - name: Install Rust ${{ matrix.msrv }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.msrv }}

      - name: cargo +${{ matrix.msrv }} check ${{ matrix.flag }}
        run: cargo check --workspace ${{ matrix.flag }}

  # msrv = Minimum Supported Rust Version
  licenses:
    name: Validate third party libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.CAOS_OAUTH_DEPLOY_KEY }}
            ${{ secrets.CAOS_OPAMP_DEPLOY_KEY }}
      - name: Install Rust ${{ env.RUST_VERSION }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Check security and licensing
        run: cargo install --locked cargo-deny && cargo deny check
      - name: Ensure that third party notices is up to date
        run: make -C license third-party-notices-check
