permissions:
  contents: read
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Checks and tests
jobs:
  onhost-e2e:
    uses: ./.github/workflows/component_onhost_e2e.yaml
    with:
      scenarios: '["migration.yaml", "remote_config.yaml"]'
      repository_endpoint: "http://nr-downloads-ohai-testing.s3-website-us-east-1.amazonaws.com/preview"
      package_version: "0.100.17452943499"
    secrets:
      NR_SYSTEM_IDENTITY_CLIENT_ID: ${{ secrets.AC_PROD_E2E_NR_SYSTEM_IDENTITY_CLIENT_ID }}
      NR_SYSTEM_IDENTITY_PRIVATE_KEY: ${{ secrets.AC_PROD_E2E_NR_SYSTEM_IDENTITY_PRIVATE_KEY }}
      E2E_ACCOUNT_ID: ${{ secrets.AC_PROD_E2E_ACCOUNT_ID }}
      E2E_API_KEY: ${{ secrets.AC_PROD_E2E_API_KEY }}
      E2E_LICENSE_KEY: ${{ secrets.AC_PROD_E2E_LICENSE_KEY }}
