name: Push/PR pipeline
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rebase:
    name: Branch needs rebase
    runs-on: ubuntu-latest
    if: github.event.pull_request
    steps:
      - uses: actions/checkout@v3
        with:
          # This job might fail for PRs with more than 50 commits. I take that as a feature.
          fetch-depth: 50
      - name: Check if PR is up to date with target branch
        run: |
          main=origin/${{ github.base_ref }}
          git fetch origin ${{ github.base_ref }}

          echo "Getting current HEAD"
          target_head=$(git show-ref -s $main)
          echo "Getting $main"
          merge_base=$(git merge-base HEAD $main)
          echo "Checking if current branch is up to date"
          if [[ ${target_head} != ${merge_base} ]]; then
            echo "Branch ${{ github.head_ref }} is not up to date with $main (${merge_base} != ${target_head}), please rebase"
            exit 1
          fi
          
          echo "${target_head} = ${merge_base}"
          exit 0

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Codespell test
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_file: ./.codespellignore
