name: 🐤 Apply onhost canaries infrastructure changes

on:
  push:
    branches:
      - main
    paths:
      - test/onhost-canaries/terraform/**
      - .github/workflows/component_onhost_canaries.yml
      - .github/workflows/push_pr_onhost_canaries_apply.yml

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: false

jobs:
  onhost_canaries:
    name: infra changes ${{ matrix.environment }}
    uses: ./.github/workflows/component_onhost_canaries_infra.yml
    permissions:
      # required to oidc AWS
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: [ staging, production ]
    with:
      environment: ${{ matrix.environment }}
      operation: apply
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_VPC_SUBNET: ${{ secrets.AWS_VPC_SUBNET }}
      AC_CANARY_WINDOWS_PASSWORD: ${{ secrets.AC_CANARY_WINDOWS_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.AC_SLACK_WEBHOOK }}
