permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
  merge_group:
# See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: coverage
env:
  # Allows to fetch multiple private repo crates with different deploy keys.
  CARGO_NET_GIT_FETCH_WITH_CLI: true
jobs:
  coverage:
    runs-on: ubuntu-latest
    name: ubuntu / stable / coverage
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.CAOS_OAUTH_DEPLOY_KEY }}
            ${{ secrets.CAOS_OPAMP_DEPLOY_KEY }}
      - name: Install stable
        uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: llvm-tools-preview
      - name: cargo install cargo-llvm-cov
        uses: taiki-e/install-action@71765c00dd3e08a5484a5b9e82a4c88b86520e0e
        # uses: taiki-e/install-action@cargo-llvm-cov
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: clean cargo workspace for coverage
        run: cargo llvm-cov clean --workspace
      - name: Generate coverage info for k8s feature
        run: cargo llvm-cov --no-report --locked --features=k8s --workspace --exclude config-migrate --lib
      - name: Generate coverage info for on-host feature
        run: cargo llvm-cov --no-report --locked --features=onhost --lib
      - name: Generate coverage report for previous tests executions
        run: cargo llvm-cov report --json --output-path jcov.info
      - name: Calculate and print total coverage
        run: |
          echo "Total functions coverage: $(jq '.data[].totals.functions.percent' jcov.info)"
          echo "Total lines coverage: $(jq '.data[].totals.lines.percent' jcov.info)"
          echo "Total regions coverage: $(jq '.data[].totals.regions.percent' jcov.info)"
          echo "Total instantiations coverage: $(jq '.data[].totals.instantiations.percent' jcov.info)"
      - name: Fail if function coverage is below 75%
        run: |
          fn_cov=$(jq '.data[].totals.functions.percent' jcov.info)
          expected=75

          if (( $(echo "$fn_cov < $expected" | bc -l) )); then
            echo "Function coverage is below ${expected}%"
            exit 1
          fi
      - name: Fail if line coverage is below 85%
        run: |
          ln_cov=$(jq '.data[].totals.lines.percent' jcov.info)
          expected=85

          if (( $(echo "$ln_cov < $expected" | bc -l) )); then
            echo "Line coverage is below ${expected}%"
            exit 1
          fi
