name: 🐤 Apply k8s canaries infrastructure changes

on:
  push:
    branches:
      - main
    paths:
      - test/k8s-canaries/terraform/**
      - .github/workflows/component_k8s_canaries_infra.yml
      - .github/workflows/push_pr_k8s_canaries_plan.yml

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: false

jobs:
  apply_k8s_canaries:
    name: infra changes ${{ matrix.canary_dir }}
    uses: ./.github/workflows/component_k8s_canaries_infra.yml
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - canary_dir: staging
          - canary_dir: production
    with:
      canary_dir: ${{ matrix.canary_dir }}
      apply: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_VPC_SUBNET: ${{ secrets.AWS_VPC_SUBNET }}
