name: Release

on:
  release:
    types:
      - released
    tags:
      - '*'

permissions:
  contents: read

jobs:
  release:
    uses: ./.github/workflows/component_release.yml
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit

  release-notes:
    uses: ./.github/workflows/shared_create_pr_public_docs_release_notes.yml
    needs: [ release ]
    with:
      version: ${{ github.event.release.tag_name }}
    secrets:
      app_id: ${{ secrets.AGENT_CONTROL_APP_ID }}
      app_private_key: ${{ secrets.AGENT_CONTROL_APP_PKEY }}
