permissions:
  contents: read
on:
  # TODO: validate when to trigger the pipeline
  push:
# See https://docs.github.com/en/actions/using-jobs/using-concurrency
name: pre-release
jobs:
  required:
    runs-on: ubuntu-latest
    name: Build and upload / ${{ matrix.toolchain }}
    strategy:
      matrix:
        arch: [arm64, amd64]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: '~1.20'
          check-latest: true

      - name: Build binaries & packages with GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist --timeout 2h

      - name: install tree
        run: apt install tree -y

      - name: Check
        run: tree ./dist/